---
title: "Code book for Getting & Cleaning Data Project"
output: html_notebook
---

Review criteria:
The submitted data set is tidy.
The Github repo contains the required scripts.
GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
The README that explains the analysis files is clear and understandable.
The work submitted for this project is the work of the student who submitted it.

Detailed informaiton is available here:
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Data for the project was taken from:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip




Analysis was performed in this order:

Download zip file

Unzip file

Review available data - train and test sets, features, activities, and subjects

Start with Measurements set: read train and test files, merge into one

Add variable names and modify for easier understanding (expand abbreviations, remove "-" and ",", "()" etc.)

Subset to only use Mean and Standard Deviation data

Add Activity data

Add Subject data

Change Activity value from integer to descriptive name

Create a new dataset that has mean of all measures by Subject and Activity

Write new dataset to a text file called "tidy_data.txt"